name: continuous integration

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/ContinuousIntegration.yml'
      - 'source/DefaultEcs/**'

jobs:
  continuous_integration:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.x'

    - name: Run tests net7.0
      run: dotnet test source\DefaultEcs.Test\DefaultEcs.Test.csproj -c SafeDebug -f net7.0 /p:TEST=true

    - name: Create package
      run: dotnet pack source\DefaultEcs\DefaultEcs.csproj -c SafeDebug -o build /p:CI_VERSION=true

    - name: Publish package
      run: nuget push build\*.nupkg
